name: "\xf0\x9f\x90\x9b Bug Report"
description: "\xe6\x8a\xa5\xe5\x91\x8a\xe9\x97\xae\xe9\xa2\x98\xef\xbc\x8c\xe5\xb8\xae\xe5\x8a\xa9\xe6\x88\x91\xe4\xbb\xac\xe6\x94\xb9\xe8\xbf\x9b GroAsk"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "\xe8\xb0\xa2\xe8\xb0\xa2\xe5\x8f\x8d\xe9\xa6\x88\xef\xbc\x81\xe8\xaf\xb7\xe5\xb0\xbd\xe9\x87\x8f\xe8\xaf\xa6\xe7\xbb\x86\xe6\x8f\x8f\xe8\xbf\xb0\xef\xbc\x8c\xe6\x96\xb9\xe4\xbe\xbf\xe6\x88\x91\xe4\xbb\xac\xe5\xbf\xab\xe9\x80\x9f\xe5\xae\x9a\xe4\xbd\x8d\xe9\x97\xae\xe9\xa2\x98\xe3\x80\x82"
  - type: textarea
    id: description
    attributes:
      label: "\xe9\x97\xae\xe9\xa2\x98\xe6\x8f\x8f\xe8\xbf\xb0"
      placeholder: "\xe5\x8f\x91\xe7\x94\x9f\xe4\xba\x86\xe4\xbb\x80\xe4\xb9\x88\xef\xbc\x9f"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "\xe5\xa4\x8d\xe7\x8e\xb0\xe6\xad\xa5\xe9\xaa\xa4"
      placeholder: "1. ...\n2. ...\n3. ..."
  - type: input
    id: version
    attributes:
      label: "GroAsk \xe7\x89\x88\xe6\x9c\xac"
      placeholder: "\xe5\xa6\x82 1.9.2\xef\xbc\x88\xe8\xae\xbe\xe7\xbd\xae\xe9\xa1\xb5\xe5\xba\x95\xe9\x83\xa8\xe6\x9f\xa5\xe7\x9c\x8b\xef\xbc\x89"
    validations:
      required: true
  - type: input
    id: macos
    attributes:
      label: "macOS \xe7\x89\x88\xe6\x9c\xac"
      placeholder: "\xe5\xa6\x82 15.3"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "\xe6\x97\xa5\xe5\xbf\x97 / \xe6\x88\xaa\xe5\x9b\xbe"
      description: "\xe5\x8f\xaf\xe9\x80\x89\xef\xbc\x8c\xe8\xb4\xb4\xe4\xb8\x8a\xe7\x9b\xb8\xe5\x85\xb3\xe6\x97\xa5\xe5\xbf\x97\xe6\x88\x96\xe6\x88\xaa\xe5\x9b\xbe"